sudo: required
language: android

addons:
  apt:
    sources:
      - sourceline: 'ppa:fdroid/fdroidserver'
    packages:
      - fdroidserver
      - openssh-client
      - lib32stdc++6
    update: true

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
  licenses:
    - 'android-sdk-license-.+'

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - yes | ./flutter/bin/flutter doctor --android-licenses
script:
  - ./flutter/bin/flutter build apk --debug
cache:
  directories:
    - $HOME/.pub-cache

after_success:
  - cp ./build/app/outputs/apk/debug/app-debug.apk ./fdroid/repo/
  - fdroid nightly -v

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
  target_branch: fdroid
  local_dir: fdroid
